Documentation/DocumentationAdmonition:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/NotNil:
  Enabled: false

Lint/Typos:
  Enabled: false

Lint/UselessAssign:
  ExcludeTypeDeclarations: true

Lint/SpecFilename:
  Excluded:
    - spec/spec_helpers.cr
